### ISSUE TITLE
Tracking Issue for PDFs

### ISSUE THREAD

**Issue by Xiphoseer** [Xiphoseer/sdo-tool#1]
## [pdf-rs](https://github.com/pdf-rs/pdf)

- [ ] `Trailer::highest_id` is actually `next_id` (why not just `size`?)
- [ ] `CCITTFaxDecode` not supported
- [ ] Type 3 Fonts don't need to have a `BaseFont`
- [ ] For Type 3 Fonts, fewer **Flags** are *Required* in the `FontDescriptor`
- [ ] `Primitive::Name(…).serialize(…)` uses `<String as Object>::serialize`, missing the `/`
- [ ] `Primitive::Array(…).serialize(…)` uses `<Vec as Object>::serialize` which uses `, ` as a separator
- [ ] No `DerefMut` on `Dictionary`
- [ ] Stream encoding is not implemented / there is no `to_primitive`
- [ ] `serialize` never produces line-breaks / doesn't allow pretty-printing
- [ ] `XRef` / `XRefTable` are designed for reading, looks difficult to adapt to writing

## [poppler](https://gitlab.freedesktop.org/poppler/poppler/)

- [ ] Embedded Font Name is not part of the glib API
- [ ] Embedded Font Name not used as name fallback

## [evince](https://gitlab.gnome.org/GNOME/evince)

- [ ] No way to get name for embedded type 3 font (except non-spec `/BaseFont`)
- [ ] Selection (`/FontBBox`) is different from Acrobat and PDF.js

**Comment by IsotoxalDev** [comment]
Is this gonna be implemented?

**Comment by Xiphoseer** [comment]
> Is this gonna be implemented?

PDF Generation is implemented already. However, there are still some rough edges because it's a custom, very low-level translation from SDO to PDF (they share a lot of similar concepts), including generating embedded Type3 fonts out of the original printer fonts inspired by how pdflatex does raster fonts.

This issue is mostly to track cases I found where other PDF programs aren't quite compatible with what I do, either because they're opinionated about it, because it's a very obscure part of the PDF spec, or because I may be doing something wrong.

**Comment by IsotoxalDev** [comment]
oh!!!
