### ISSUE TITLE
Tracking Issue for 1.0

### ISSUE THREAD

**Issue by Xiphoseer** [Xiphoseer/sdo-tool#4]
- [ ] Italic and Bold font modifiers
- [ ] Using modified date in exports
- [ ] `Export` trait
- [ ] Add a Document / `sdoc` struct to the `signum` crate
- [ ] Convert fonts to TTF (optional)

**Comment by Xiphoseer** [comment]
Idea: Unicode Normalization of `ToUnicode` mapping. `FRAKTUR1` mapping curently uses the dedicated unicode symbols ſ (Latin Small Letter Long s) and ﬅ (Latin Small Ligature S T), which results in output like this

> Frakturſchrift iﬅ mit Signum natürlich auch möglich!

which is typograpically more accurate but maybe should be normalized _before_ ToUnicode.
